# Generated by Django 4.0.4 on 2024-01-27 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Automobile',
            new_name='Vehicle',
        ),
    ]
